apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collector-artifacts
  namespace: collectors
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
