apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flink
resources:
  - operator-helm.yaml
  - eth-sentiment-trading-job.yaml
  - eth-sentiment-analysis-job.yaml
  - kafka2milvus.yaml
  - employee-message-processor.yaml
  - realtime-riskcontrol-embedding-job.yaml
