apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: realtime-riskcontrol-embedding
  namespace: flink
spec:
  flinkVersion: v1_18
  flinkImage: "apache/flink-kubernetes-operator:1.2.0"
  ingress:
    class: nginx
    labels:
      app: realtime-riskcontrol-embedding
  jobManager:
    resource:
      cpu: 1
      memory: "1024m"
    replicas: 1
  taskManager:
    resource:
      cpu: 2
      memory: "2048m"
    numberOfTaskSlots: 4
  persistence: true
  job:
    jarURI: local:///opt/flink/jobs/realtime-riskcontrol-embedding-job.jar
    parallelism: 2
    upgradeMode: savepoint
    stateRetention:
      failOnTTLInUse: true
  stateBackend:
    type: hashmap
  checkpointing:
    checkpointTimeout: 10000
    maxConcurrentCheckpoints: 1
    unalignedCheckpoints: false
  env:
    - name: S3_ENDPOINT
      value: "http://minio.data.svc.cluster.local:9000"
    - name: S3_ACCESS_KEY
      value: "minioadmin"
    - name: S3_SECRET_KEY
      value: "minioadmin"
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: "kafka:29092"
    - name: TZ
      value: "Asia/Shanghai"
