apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: flink
---
apiVersion: v1
kind: Namespace
metadata:
  name: collectors
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops
